package com.sekusarisu.yanami.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

/**
 * 主题颜色方案枚举
 *
 * 每种预设颜色包含亮色和暗色两套 MD3 ColorScheme。 DYNAMIC 表示使用系统壁纸动态取色（仅 Android 12+）。
 */
enum class ThemeColor(
        val key: String,
        val seedColor: Color,
        val lightScheme: ColorScheme?,
        val darkScheme: ColorScheme?
) {
    /** 动态壁纸取色（Android 12+） */
    DYNAMIC(key = "dynamic", seedColor = Color(0xFFFF1493), lightScheme = null, darkScheme = null),

    /** 青绿 — 默认（粉色版：白卡片 + 亮粉边框 + 粉紫渐变） */
    TEAL(
            key = "teal",
            seedColor = Color(0xFFFF1493),
            lightScheme =
                    lightColorScheme(
                            primary = Color(0xFFFF1493),
                            onPrimary = Color(0xFFFFFFFF),
                            primaryContainer = Color(0xFFFF80AB),
                            onPrimaryContainer = Color(0xFF880E4F),
                            secondary = Color(0xFF9C27B0),
                            onSecondary = Color(0xFFFFFFFF),
                            secondaryContainer = Color(0xFFE1BEE7),
                            onSecondaryContainer = Color(0xFF4A148C),
                            tertiary = Color(0xFF7C4DFF),
                            onTertiary = Color(0xFFFFFFFF),
                            tertiaryContainer = Color(0xFFD1C4E9),
                            onTertiaryContainer = Color(0xFF311B92),
                            error = Color(0xFFBA1A1A),
                            onError = Color(0xFFFFFFFF),
                            errorContainer = Color(0xFFFFDAD6),
                            onErrorContainer = Color(0xFF410002),
                            background = Color(0xFFFFF0F5),
                            onBackground = Color(0xFF2D1B24),
                            surface = Color(0xFFFFFFFF),
                            onSurface = Color(0xFF2D1B24),
                            surfaceVariant = Color(0xFFFFF0F5),
                            onSurfaceVariant = Color(0xFF6B5B66),
                            outline = Color(0xFFFF4081),
                            outlineVariant = Color(0xFFFF80AB),
                    ),
            darkScheme =
                    darkColorScheme(
                            primary = Color(0xFF5CDAC4),
                            onPrimary = Color(0xFF003830),
                            primaryContainer = Color(0xFF005046),
                            onPrimaryContainer = Color(0xFF7AF7E0),
                            secondary = Color(0xFFB1CCC4),
                            onSecondary = Color(0xFF1D352F),
                            secondaryContainer = Color(0xFF334B46),
                            onSecondaryContainer = Color(0xFFFF8FAB),
                            tertiary = Color(0xFFAACBE3),
                            onTertiary = Color(0xFF113447),
                            tertiaryContainer = Color(0xFF2B4A5F),
                            onTertiaryContainer = Color(0xFFFF8FAB),
                            error = Color(0xFFFFB4AB),
                            onError = Color(0xFF690005),
                            errorContainer = Color(0xFF93000A),
                            onErrorContainer = Color(0xFFFFDAD6),
                            background = Color(0xFF191C1B),
                            onBackground = Color(0xFFE1E3E0),
                            surface = Color(0xFF191C1B),
                            onSurface = Color(0xFFE1E3E0),
                            surfaceVariant = Color(0xFF3F4945),
                            onSurfaceVariant = Color(0xFFBEC9C4),
                            outline = Color(0xFF89938F),
                            outlineVariant = Color(0xFF3F4945),
                    )
    ),

    /** 蓝色 */
    BLUE(
            key = "blue",
            seedColor = Color(0xFF1565C0),
            lightScheme =
                    lightColorScheme(
                            primary = Color(0xFF1565C0),
                            onPrimary = Color(0xFFFFFFFF),
                            primaryContainer = Color(0xFFD4E3FF),
                            onPrimaryContainer = Color(0xFF001C3A),
                            secondary = Color(0xFF555F71),
                            onSecondary = Color(0xFFFFFFFF),
                            secondaryContainer = Color(0xFFD9E3F8),
                            onSecondaryContainer = Color(0xFF121C2B),
                            tertiary = Color(0xFF6E5676),
                            onTertiary = Color(0xFFFFFFFF),
                            tertiaryContainer = Color(0xFFF8D8FE),
                            onTertiaryContainer = Color(0xFF271430),
                            error = Color(0xFFBA1A1A),
                            onError = Color(0xFFFFFFFF),
                            errorContainer = Color(0xFFFFDAD6),
                            onErrorContainer = Color(0xFF410002),
                            background = Color(0xFFFDFBFF),
                            onBackground = Color(0xFF1B1B1F),
                            surface = Color(0xFFFDFBFF),
                            onSurface = Color(0xFF1B1B1F),
                            surfaceVariant = Color(0xFFE0E2EC),
                            onSurfaceVariant = Color(0xFF44474E),
                            outline = Color(0xFF74777F),
                            outlineVariant = Color(0xFFC4C6CF),
                    ),
            darkScheme =
                    darkColorScheme(
                            primary = Color(0xFFA5C8FF),
                            onPrimary = Color(0xFF00325E),
                            primaryContainer = Color(0xFF004A85),
                            onPrimaryContainer = Color(0xFFD4E3FF),
                            secondary = Color(0xFFBDC7DB),
                            onSecondary = Color(0xFF273141),
                            secondaryContainer = Color(0xFF3E4758),
                            onSecondaryContainer = Color(0xFFD9E3F8),
                            tertiary = Color(0xFFDBBCE2),
                            onTertiary = Color(0xFF3D2846),
                            tertiaryContainer = Color(0xFF553F5D),
                            onTertiaryContainer = Color(0xFFF8D8FE),
                            error = Color(0xFFFFB4AB),
                            onError = Color(0xFF690005),
                            errorContainer = Color(0xFF93000A),
                            onErrorContainer = Color(0xFFFFDAD6),
                            background = Color(0xFF1B1B1F),
                            onBackground = Color(0xFFE4E2E6),
                            surface = Color(0xFF1B1B1F),
                            onSurface = Color(0xFFE4E2E6),
                            surfaceVariant = Color(0xFF44474E),
                            onSurfaceVariant = Color(0xFFC4C6CF),
                            outline = Color(0xFF8E9099),
                            outlineVariant = Color(0xFF44474E),
                    )
    ),

    /** 紫色 */
    PURPLE(
            key = "purple",
            seedColor = Color(0xFF7B1FA2),
            lightScheme =
                    lightColorScheme(
                            primary = Color(0xFF7B1FA2),
                            onPrimary = Color(0xFFFFFFFF),
                            primaryContainer = Color(0xFFF1DAFF),
                            onPrimaryContainer = Color(0xFF2C004E),
                            secondary = Color(0xFF665A6F),
                            onSecondary = Color(0xFFFFFFFF),
                            secondaryContainer = Color(0xFFEDDEF7),
                            onSecondaryContainer = Color(0xFF21182A),
                            tertiary = Color(0xFF805159),
                            onTertiary = Color(0xFFFFFFFF),
                            tertiaryContainer = Color(0xFFFFD9DE),
                            onTertiaryContainer = Color(0xFF321018),
                            error = Color(0xFFBA1A1A),
                            onError = Color(0xFFFFFFFF),
                            errorContainer = Color(0xFFFFDAD6),
                            onErrorContainer = Color(0xFF410002),
                            background = Color(0xFFFFFBFF),
                            onBackground = Color(0xFF1E1A20),
                            surface = Color(0xFFFFFBFF),
                            onSurface = Color(0xFF1E1A20),
                            surfaceVariant = Color(0xFFE9DFEA),
                            onSurfaceVariant = Color(0xFF4B454D),
                            outline = Color(0xFF7C757E),
                            outlineVariant = Color(0xFFCCC4CE),
                    ),
            darkScheme =
                    darkColorScheme(
                            primary = Color(0xFFDEB7FF),
                            onPrimary = Color(0xFF49007A),
                            primaryContainer = Color(0xFF620089),
                            onPrimaryContainer = Color(0xFFF1DAFF),
                            secondary = Color(0xFFD1C2DB),
                            onSecondary = Color(0xFF362D40),
                            secondaryContainer = Color(0xFF4D4357),
                            onSecondaryContainer = Color(0xFFEDDEF7),
                            tertiary = Color(0xFFF3B7BF),
                            onTertiary = Color(0xFF4B252C),
                            tertiaryContainer = Color(0xFF653A42),
                            onTertiaryContainer = Color(0xFFFFD9DE),
                            error = Color(0xFFFFB4AB),
                            onError = Color(0xFF690005),
                            errorContainer = Color(0xFF93000A),
                            onErrorContainer = Color(0xFFFFDAD6),
                            background = Color(0xFF1E1A20),
                            onBackground = Color(0xFFE8E0E5),
                            surface = Color(0xFF1E1A20),
                            onSurface = Color(0xFFE8E0E5),
                            surfaceVariant = Color(0xFF4B454D),
                            onSurfaceVariant = Color(0xFFCCC4CE),
                            outline = Color(0xFF968E98),
                            outlineVariant = Color(0xFF4B454D),
                    )
    ),

    /** 粉色 */
    PINK(
            key = "pink",
            seedColor = Color(0xFFC2185B),
            lightScheme =
                    lightColorScheme(
                            primary = Color(0xFFC2185B),
                            onPrimary = Color(0xFFFFFFFF),
                            primaryContainer = Color(0xFFFFD9E1),
                            onPrimaryContainer = Color(0xFF3F001B),
                            secondary = Color(0xFF75565D),
                            onSecondary = Color(0xFFFFFFFF),
                            secondaryContainer = Color(0xFFFFD9E1),
                            onSecondaryContainer = Color(0xFF2B151B),
                            tertiary = Color(0xFF7C5635),
                            onTertiary = Color(0xFFFFFFFF),
                            tertiaryContainer = Color(0xFFFFDCC3),
                            onTertiaryContainer = Color(0xFF2E1500),
                            error = Color(0xFFBA1A1A),
                            onError = Color(0xFFFFFFFF),
                            errorContainer = Color(0xFFFFDAD6),
                            onErrorContainer = Color(0xFF410002),
                            background = Color(0xFFFFFBFF),
                            onBackground = Color(0xFF201A1C),
                            surface = Color(0xFFFFFBFF),
                            onSurface = Color(0xFF201A1C),
                            surfaceVariant = Color(0xFFF3DDE1),
                            onSurfaceVariant = Color(0xFF514347),
                            outline = Color(0xFF847377),
                            outlineVariant = Color(0xFFD6C2C5),
                    ),
            darkScheme =
                    darkColorScheme(
                            primary = Color(0xFFFFB1C4),
                            onPrimary = Color(0xFF650030),
                            primaryContainer = Color(0xFF8E0044),
                            onPrimaryContainer = Color(0xFFFFD9E1),
                            secondary = Color(0xFFE4BDC5),
                            onSecondary = Color(0xFF43292F),
                            secondaryContainer = Color(0xFF5B3F46),
                            onSecondaryContainer = Color(0xFFFFD9E1),
                            tertiary = Color(0xFFEFBD94),
                            onTertiary = Color(0xFF48290B),
                            tertiaryContainer = Color(0xFF623F1F),
                            onTertiaryContainer = Color(0xFFFFDCC3),
                            error = Color(0xFFFFB4AB),
                            onError = Color(0xFF690005),
                            errorContainer = Color(0xFF93000A),
                            onErrorContainer = Color(0xFFFFDAD6),
                            background = Color(0xFF201A1C),
                            onBackground = Color(0xFFEBE0E1),
                            surface = Color(0xFF201A1C),
                            onSurface = Color(0xFFEBE0E1),
                            surfaceVariant = Color(0xFF514347),
                            onSurfaceVariant = Color(0xFFD6C2C5),
                            outline = Color(0xFF9E8C90),
                            outlineVariant = Color(0xFF514347),
                    )
    ),

    /** 橙色 */
    ORANGE(
            key = "orange",
            seedColor = Color(0xFFE65100),
            lightScheme =
                    lightColorScheme(
                            primary = Color(0xFFBF360C),
                            onPrimary = Color(0xFFFFFFFF),
                            primaryContainer = Color(0xFFFFDBCF),
                            onPrimaryContainer = Color(0xFF3A0B00),
                            secondary = Color(0xFF77574C),
                            onSecondary = Color(0xFFFFFFFF),
                            secondaryContainer = Color(0xFFFFDBCF),
                            onSecondaryContainer = Color(0xFF2C160D),
                            tertiary = Color(0xFF6B5E2F),
                            onTertiary = Color(0xFFFFFFFF),
                            tertiaryContainer = Color(0xFFF4E2A7),
                            onTertiaryContainer = Color(0xFF231B00),
                            error = Color(0xFFBA1A1A),
                            onError = Color(0xFFFFFFFF),
                            errorContainer = Color(0xFFFFDAD6),
                            onErrorContainer = Color(0xFF410002),
                            background = Color(0xFFFFFBFF),
                            onBackground = Color(0xFF201A17),
                            surface = Color(0xFFFFFBFF),
                            onSurface = Color(0xFF201A17),
                            surfaceVariant = Color(0xFFF5DED5),
                            onSurfaceVariant = Color(0xFF53443D),
                            outline = Color(0xFF85746C),
                            outlineVariant = Color(0xFFD8C2B8),
                    ),
            darkScheme =
                    darkColorScheme(
                            primary = Color(0xFFFFB59C),
                            onPrimary = Color(0xFF5F1600),
                            primaryContainer = Color(0xFF862200),
                            onPrimaryContainer = Color(0xFFFFDBCF),
                            secondary = Color(0xFFE7BEAF),
                            onSecondary = Color(0xFF442A21),
                            secondaryContainer = Color(0xFF5D4036),
                            onSecondaryContainer = Color(0xFFFFDBCF),
                            tertiary = Color(0xFFD7C68D),
                            onTertiary = Color(0xFF3A3005),
                            tertiaryContainer = Color(0xFF52461A),
                            onTertiaryContainer = Color(0xFFF4E2A7),
                            error = Color(0xFFFFB4AB),
                            onError = Color(0xFF690005),
                            errorContainer = Color(0xFF93000A),
                            onErrorContainer = Color(0xFFFFDAD6),
                            background = Color(0xFF201A17),
                            onBackground = Color(0xFFEDE0DB),
                            surface = Color(0xFF201A17),
                            onSurface = Color(0xFFEDE0DB),
                            surfaceVariant = Color(0xFF53443D),
                            onSurfaceVariant = Color(0xFFD8C2B8),
                            outline = Color(0xFFA08D84),
                            outlineVariant = Color(0xFF53443D),
                    )
    ),

    /** 绿色 */
    GREEN(
            key = "green",
            seedColor = Color(0xFF2E7D32),
            lightScheme =
                    lightColorScheme(
                            primary = Color(0xFF2E7D32),
                            onPrimary = Color(0xFFFFFFFF),
                            primaryContainer = Color(0xFFA8F5AB),
                            onPrimaryContainer = Color(0xFF002106),
                            secondary = Color(0xFF52634F),
                            onSecondary = Color(0xFFFFFFFF),
                            secondaryContainer = Color(0xFFD5E8CF),
                            onSecondaryContainer = Color(0xFF101F10),
                            tertiary = Color(0xFF38656A),
                            onTertiary = Color(0xFFFFFFFF),
                            tertiaryContainer = Color(0xFFBCEBF1),
                            onTertiaryContainer = Color(0xFF002023),
                            error = Color(0xFFBA1A1A),
                            onError = Color(0xFFFFFFFF),
                            errorContainer = Color(0xFFFFDAD6),
                            onErrorContainer = Color(0xFF410002),
                            background = Color(0xFFFCFDF7),
                            onBackground = Color(0xFF1A1C19),
                            surface = Color(0xFFFCFDF7),
                            onSurface = Color(0xFF1A1C19),
                            surfaceVariant = Color(0xFFDEE5D9),
                            onSurfaceVariant = Color(0xFF424940),
                            outline = Color(0xFF72796F),
                            outlineVariant = Color(0xFFC2C9BD),
                    ),
            darkScheme =
                    darkColorScheme(
                            primary = Color(0xFF8CD891),
                            onPrimary = Color(0xFF003910),
                            primaryContainer = Color(0xFF0E5319),
                            onPrimaryContainer = Color(0xFFA8F5AB),
                            secondary = Color(0xFFB9CCB3),
                            onSecondary = Color(0xFF253424),
                            secondaryContainer = Color(0xFF3B4B39),
                            onSecondaryContainer = Color(0xFFD5E8CF),
                            tertiary = Color(0xFFA0CFD4),
                            onTertiary = Color(0xFF00373B),
                            tertiaryContainer = Color(0xFF1F4D52),
                            onTertiaryContainer = Color(0xFFBCEBF1),
                            error = Color(0xFFFFB4AB),
                            onError = Color(0xFF690005),
                            errorContainer = Color(0xFF93000A),
                            onErrorContainer = Color(0xFFFFDAD6),
                            background = Color(0xFF1A1C19),
                            onBackground = Color(0xFFE2E3DD),
                            surface = Color(0xFF1A1C19),
                            onSurface = Color(0xFFE2E3DD),
                            surfaceVariant = Color(0xFF424940),
                            onSurfaceVariant = Color(0xFFC2C9BD),
                            outline = Color(0xFF8C9388),
                            outlineVariant = Color(0xFF424940),
                    )
    ),

    /** 红色 (Material Theme Builder) */
    RED(
            key = "red",
            seedColor = Color(0xFF8F4C38),
            lightScheme =
                    lightColorScheme(
                            primary = Color(0xFF8F4C38),
                            onPrimary = Color(0xFFFFFFFF),
                            primaryContainer = Color(0xFFFFDBD1),
                            onPrimaryContainer = Color(0xFF723523),
                            secondary = Color(0xFF77574E),
                            onSecondary = Color(0xFFFFFFFF),
                            secondaryContainer = Color(0xFFFFDBD1),
                            onSecondaryContainer = Color(0xFF5D4037),
                            tertiary = Color(0xFF6C5D2F),
                            onTertiary = Color(0xFFFFFFFF),
                            tertiaryContainer = Color(0xFFF5E1A7),
                            onTertiaryContainer = Color(0xFF534619),
                            error = Color(0xFFBA1A1A),
                            onError = Color(0xFFFFFFFF),
                            errorContainer = Color(0xFFFFDAD6),
                            onErrorContainer = Color(0xFF93000A),
                            background = Color(0xFFFFF8F6),
                            onBackground = Color(0xFF231917),
                            surface = Color(0xFFFFF8F6),
                            onSurface = Color(0xFF231917),
                            surfaceVariant = Color(0xFFF5DED8),
                            onSurfaceVariant = Color(0xFF53433F),
                            outline = Color(0xFF85736E),
                            outlineVariant = Color(0xFFD8C2BC),
                    ),
            darkScheme =
                    darkColorScheme(
                            primary = Color(0xFFFFB5A0),
                            onPrimary = Color(0xFF561F0F),
                            primaryContainer = Color(0xFF723523),
                            onPrimaryContainer = Color(0xFFFFDBD1),
                            secondary = Color(0xFFE7BDB2),
                            onSecondary = Color(0xFF442A22),
                            secondaryContainer = Color(0xFF5D4037),
                            onSecondaryContainer = Color(0xFFFFDBD1),
                            tertiary = Color(0xFFD8C58D),
                            onTertiary = Color(0xFF3B2F05),
                            tertiaryContainer = Color(0xFF534619),
                            onTertiaryContainer = Color(0xFFF5E1A7),
                            error = Color(0xFFFFB4AB),
                            onError = Color(0xFF690005),
                            errorContainer = Color(0xFF93000A),
                            onErrorContainer = Color(0xFFFFDAD6),
                            background = Color(0xFF1A110F),
                            onBackground = Color(0xFFF1DFDA),
                            surface = Color(0xFF1A110F),
                            onSurface = Color(0xFFF1DFDA),
                            surfaceVariant = Color(0xFF53433F),
                            onSurfaceVariant = Color(0xFFD8C2BC),
                            outline = Color(0xFFA08C87),
                            outlineVariant = Color(0xFF53433F),
                    )
    ),

    /** 橄榄绿 (Material Theme Builder) */
    GREEN_MTB(
            key = "green_mtb",
            seedColor = Color(0xFF4C662B),
            lightScheme =
                    lightColorScheme(
                            primary = Color(0xFF4C662B),
                            onPrimary = Color(0xFFFFFFFF),
                            primaryContainer = Color(0xFFCDEDA3),
                            onPrimaryContainer = Color(0xFF354E16),
                            secondary = Color(0xFF586249),
                            onSecondary = Color(0xFFFFFFFF),
                            secondaryContainer = Color(0xFFDCE7C8),
                            onSecondaryContainer = Color(0xFF404A33),
                            tertiary = Color(0xFF386663),
                            onTertiary = Color(0xFFFFFFFF),
                            tertiaryContainer = Color(0xFFBCECE7),
                            onTertiaryContainer = Color(0xFF1F4E4B),
                            error = Color(0xFFBA1A1A),
                            onError = Color(0xFFFFFFFF),
                            errorContainer = Color(0xFFFFDAD6),
                            onErrorContainer = Color(0xFF93000A),
                            background = Color(0xFFF9FAEF),
                            onBackground = Color(0xFF1A1C16),
                            surface = Color(0xFFF9FAEF),
                            onSurface = Color(0xFF1A1C16),
                            surfaceVariant = Color(0xFFE1E4D5),
                            onSurfaceVariant = Color(0xFF44483D),
                            outline = Color(0xFF75796C),
                            outlineVariant = Color(0xFFC5C8BA),
                    ),
            darkScheme =
                    darkColorScheme(
                            primary = Color(0xFFB1D18A),
                            onPrimary = Color(0xFF1F3701),
                            primaryContainer = Color(0xFF354E16),
                            onPrimaryContainer = Color(0xFFCDEDA3),
                            secondary = Color(0xFFBFCBAD),
                            onSecondary = Color(0xFF2A331E),
                            secondaryContainer = Color(0xFF404A33),
                            onSecondaryContainer = Color(0xFFDCE7C8),
                            tertiary = Color(0xFFA0D0CB),
                            onTertiary = Color(0xFF003735),
                            tertiaryContainer = Color(0xFF1F4E4B),
                            onTertiaryContainer = Color(0xFFBCECE7),
                            error = Color(0xFFFFB4AB),
                            onError = Color(0xFF690005),
                            errorContainer = Color(0xFF93000A),
                            onErrorContainer = Color(0xFFFFDAD6),
                            background = Color(0xFF12140E),
                            onBackground = Color(0xFFE2E3D8),
                            surface = Color(0xFF12140E),
                            onSurface = Color(0xFFE2E3D8),
                            surfaceVariant = Color(0xFF44483D),
                            onSurfaceVariant = Color(0xFFC5C8BA),
                            outline = Color(0xFF8F9285),
                            outlineVariant = Color(0xFF44483D),
                    )
    ),

    /** 靛蓝 (Material Theme Builder) */
    BLUE_MTB(
            key = "blue_mtb",
            seedColor = Color(0xFF415F91),
            lightScheme =
                    lightColorScheme(
                            primary = Color(0xFF415F91),
                            onPrimary = Color(0xFFFFFFFF),
                            primaryContainer = Color(0xFFD6E3FF),
                            onPrimaryContainer = Color(0xFF284777),
                            secondary = Color(0xFF565F71),
                            onSecondary = Color(0xFFFFFFFF),
                            secondaryContainer = Color(0xFFDAE2F9),
                            onSecondaryContainer = Color(0xFF3E4759),
                            tertiary = Color(0xFF705575),
                            onTertiary = Color(0xFFFFFFFF),
                            tertiaryContainer = Color(0xFFFAD8FD),
                            onTertiaryContainer = Color(0xFF573E5C),
                            error = Color(0xFFBA1A1A),
                            onError = Color(0xFFFFFFFF),
                            errorContainer = Color(0xFFFFDAD6),
                            onErrorContainer = Color(0xFF93000A),
                            background = Color(0xFFF9F9FF),
                            onBackground = Color(0xFF191C20),
                            surface = Color(0xFFF9F9FF),
                            onSurface = Color(0xFF191C20),
                            surfaceVariant = Color(0xFFE0E2EC),
                            onSurfaceVariant = Color(0xFF44474E),
                            outline = Color(0xFF74777F),
                            outlineVariant = Color(0xFFC4C6D0),
                    ),
            darkScheme =
                    darkColorScheme(
                            primary = Color(0xFFAAC7FF),
                            onPrimary = Color(0xFF0A305F),
                            primaryContainer = Color(0xFF284777),
                            onPrimaryContainer = Color(0xFFD6E3FF),
                            secondary = Color(0xFFBEC6DC),
                            onSecondary = Color(0xFF283141),
                            secondaryContainer = Color(0xFF3E4759),
                            onSecondaryContainer = Color(0xFFDAE2F9),
                            tertiary = Color(0xFFDDBCE0),
                            onTertiary = Color(0xFF3F2844),
                            tertiaryContainer = Color(0xFF573E5C),
                            onTertiaryContainer = Color(0xFFFAD8FD),
                            error = Color(0xFFFFB4AB),
                            onError = Color(0xFF690005),
                            errorContainer = Color(0xFF93000A),
                            onErrorContainer = Color(0xFFFFDAD6),
                            background = Color(0xFF111318),
                            onBackground = Color(0xFFE2E2E9),
                            surface = Color(0xFF111318),
                            onSurface = Color(0xFFE2E2E9),
                            surfaceVariant = Color(0xFF44474E),
                            onSurfaceVariant = Color(0xFFC4C6D0),
                            outline = Color(0xFF8E9099),
                            outlineVariant = Color(0xFF44474E),
                    )
    ),

    /** 金黄 (Material Theme Builder) */
    YELLOW(
            key = "yellow",
            seedColor = Color(0xFF6D5E0F),
            lightScheme =
                    lightColorScheme(
                            primary = Color(0xFF6D5E0F),
                            onPrimary = Color(0xFFFFFFFF),
                            primaryContainer = Color(0xFFF8E287),
                            onPrimaryContainer = Color(0xFF534600),
                            secondary = Color(0xFF665E40),
                            onSecondary = Color(0xFFFFFFFF),
                            secondaryContainer = Color(0xFFEEE2BC),
                            onSecondaryContainer = Color(0xFF4E472A),
                            tertiary = Color(0xFF43664E),
                            onTertiary = Color(0xFFFFFFFF),
                            tertiaryContainer = Color(0xFFC5ECCE),
                            onTertiaryContainer = Color(0xFF2C4E38),
                            error = Color(0xFFBA1A1A),
                            onError = Color(0xFFFFFFFF),
                            errorContainer = Color(0xFFFFDAD6),
                            onErrorContainer = Color(0xFF93000A),
                            background = Color(0xFFFFF9EE),
                            onBackground = Color(0xFF1E1B13),
                            surface = Color(0xFFFFF9EE),
                            onSurface = Color(0xFF1E1B13),
                            surfaceVariant = Color(0xFFEAE2D0),
                            onSurfaceVariant = Color(0xFF4B4739),
                            outline = Color(0xFF7C7767),
                            outlineVariant = Color(0xFFCDC6B4),
                    ),
            darkScheme =
                    darkColorScheme(
                            primary = Color(0xFFDBC66E),
                            onPrimary = Color(0xFF3A3000),
                            primaryContainer = Color(0xFF534600),
                            onPrimaryContainer = Color(0xFFF8E287),
                            secondary = Color(0xFFD1C6A1),
                            onSecondary = Color(0xFF363016),
                            secondaryContainer = Color(0xFF4E472A),
                            onSecondaryContainer = Color(0xFFEEE2BC),
                            tertiary = Color(0xFFA9D0B3),
                            onTertiary = Color(0xFF143723),
                            tertiaryContainer = Color(0xFF2C4E38),
                            onTertiaryContainer = Color(0xFFC5ECCE),
                            error = Color(0xFFFFB4AB),
                            onError = Color(0xFF690005),
                            errorContainer = Color(0xFF93000A),
                            onErrorContainer = Color(0xFFFFDAD6),
                            background = Color(0xFF15130B),
                            onBackground = Color(0xFFE8E2D4),
                            surface = Color(0xFF15130B),
                            onSurface = Color(0xFFE8E2D4),
                            surfaceVariant = Color(0xFF4B4739),
                            onSurfaceVariant = Color(0xFFCDC6B4),
                            outline = Color(0xFF969080),
                            outlineVariant = Color(0xFF4B4739),
                    )
    );

    companion object {
        /** 根据 key 字符串获取对应枚举，找不到则返回 DYNAMIC */
        fun fromKey(key: String): ThemeColor = entries.find { it.key == key } ?: TEAL
    }
}
