name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Create Keystore
        run: |
          keytool -genkeypair -v -keystore yanami.keystore -alias yanami -keyalg RSA -keysize 2048 -validity 10000 -storepass 123456 -keypass 123456 -dname "CN=Yanami Pink, OU=Dev, O=Yanami, L=HK, ST=HK, C=CN"

      - name: Set Env Variables
        run: |
          echo "KEYSTORE_FILE=yanami.keystore" >> $GITHUB_ENV
          echo "KEYSTORE_PASSWORD=123456" >> $GITHUB_ENV
          echo "KEY_ALIAS=yanami" >> $GITHUB_ENV
          echo "KEY_PASSWORD=123456" >> $GITHUB_ENV

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease --no-daemon

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: yanami-pink-apk
          path: app/build/outputs/apk/release/app-release.apk

